### PR TITLE
I have made some changes on readme.md file on the installation sectio…

### PR DESCRIPTION
**Pull request by imranertaza**
Hi
Today I have made a little bit of contribution to this project. 

1) I have made some changes to the readme.md file on the installation section so that it gets easier for contributors to install the project.
2) I have added the .env.example file which did not exist in our project.
3) I have added .idea directory line into the .gitignore file so that .idea folder does not push into this project.

Please check and let me know if any changes are needed.
Thank you

### CODE REVIEW

**Review by edrisranjbar — CHANGES_REQUESTED** [review]
everything fine, except for .env.example file in which the DB_CONNECTION should be set as SQLIte as it is in the example below:
```
DB_CONNECTION=sqlite
```

**Review by edrisranjbar — APPROVED** [review]
Thanks a lot for making the changes. just one other thing: when we have sqlite as a database connection driver; we do not need DB_HOST, PORT and DATABASE. so we need to remove them all.

again, Thanks ❤️ .

**Comment by imranertaza** [comment]
Ok, if you want, I will remove these DB_HOST, PORT and DATABASE from the file. But before removing, may I know what will contributors do when any contributor want to use mysql?
Will they add these lines again to their local repository to use mysql?
I think, we can comment off those lines so that whenever they want to use mysql, they can uncomment it and use mysql. What do you think? Please let me know.
Thank you

**Comment by edrisranjbar** [comment]
I guess making SQLITE default makes more sense because it is easier to launch and does not require username, password or etc. but as you it is good to make MYSQL lines commented:
```env
#DB_CONNECTION=mysql
#DB_HOST=127.0.0.1
#DB_PORT=3306
#DB_DATABASE=laravel
#DB_USERNAME=root
#DB_PASSWORD=
```

**Comment by imranertaza** [comment]
Ok, Thank you for your confirmation. I will comment those mysql lines soon. Thank you

**Pull request merged**
